#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinUniversity.Resource", IsApplication=true)]

namespace XamarinUniversity
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Refractored.Fab.Resource.Attribute.fab_colorDisabled = global::XamarinUniversity.Resource.Attribute.fab_colorDisabled;
			global::Refractored.Fab.Resource.Attribute.fab_colorNormal = global::XamarinUniversity.Resource.Attribute.fab_colorNormal;
			global::Refractored.Fab.Resource.Attribute.fab_colorPressed = global::XamarinUniversity.Resource.Attribute.fab_colorPressed;
			global::Refractored.Fab.Resource.Attribute.fab_colorRipple = global::XamarinUniversity.Resource.Attribute.fab_colorRipple;
			global::Refractored.Fab.Resource.Attribute.fab_shadow = global::XamarinUniversity.Resource.Attribute.fab_shadow;
			global::Refractored.Fab.Resource.Attribute.fab_size = global::XamarinUniversity.Resource.Attribute.fab_size;
			global::Refractored.Fab.Resource.Attribute.layoutManager = global::XamarinUniversity.Resource.Attribute.layoutManager;
			global::Refractored.Fab.Resource.Attribute.reverseLayout = global::XamarinUniversity.Resource.Attribute.reverseLayout;
			global::Refractored.Fab.Resource.Attribute.spanCount = global::XamarinUniversity.Resource.Attribute.spanCount;
			global::Refractored.Fab.Resource.Attribute.stackFromEnd = global::XamarinUniversity.Resource.Attribute.stackFromEnd;
			global::Refractored.Fab.Resource.Color.fab_material_blue_500 = global::XamarinUniversity.Resource.Color.fab_material_blue_500;
			global::Refractored.Fab.Resource.Dimension.fab_elevation_lollipop = global::XamarinUniversity.Resource.Dimension.fab_elevation_lollipop;
			global::Refractored.Fab.Resource.Dimension.fab_scroll_threshold = global::XamarinUniversity.Resource.Dimension.fab_scroll_threshold;
			global::Refractored.Fab.Resource.Dimension.fab_shadow_size = global::XamarinUniversity.Resource.Dimension.fab_shadow_size;
			global::Refractored.Fab.Resource.Dimension.fab_size_mini = global::XamarinUniversity.Resource.Dimension.fab_size_mini;
			global::Refractored.Fab.Resource.Dimension.fab_size_normal = global::XamarinUniversity.Resource.Dimension.fab_size_normal;
			global::Refractored.Fab.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::XamarinUniversity.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::Refractored.Fab.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity = global::XamarinUniversity.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity;
			global::Refractored.Fab.Resource.Dimension.item_touch_helper_swipe_escape_velocity = global::XamarinUniversity.Resource.Dimension.item_touch_helper_swipe_escape_velocity;
			global::Refractored.Fab.Resource.Drawable.fab_shadow = global::XamarinUniversity.Resource.Drawable.fab_shadow;
			global::Refractored.Fab.Resource.Drawable.fab_shadow_mini = global::XamarinUniversity.Resource.Drawable.fab_shadow_mini;
			global::Refractored.Fab.Resource.Id.item_touch_helper_previous_elevation = global::XamarinUniversity.Resource.Id.item_touch_helper_previous_elevation;
			global::Refractored.Fab.Resource.Id.mini = global::XamarinUniversity.Resource.Id.mini;
			global::Refractored.Fab.Resource.Id.normal = global::XamarinUniversity.Resource.Id.normal;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton = global::XamarinUniversity.Resource.Styleable.FloatingActionButton;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::XamarinUniversity.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::XamarinUniversity.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::XamarinUniversity.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::XamarinUniversity.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::XamarinUniversity.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_size = global::XamarinUniversity.Resource.Styleable.FloatingActionButton_fab_size;
			global::Refractored.Fab.Resource.Styleable.RecyclerView = global::XamarinUniversity.Resource.Styleable.RecyclerView;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_android_descendantFocusability = global::XamarinUniversity.Resource.Styleable.RecyclerView_android_descendantFocusability;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_android_orientation = global::XamarinUniversity.Resource.Styleable.RecyclerView_android_orientation;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_layoutManager = global::XamarinUniversity.Resource.Styleable.RecyclerView_layoutManager;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_reverseLayout = global::XamarinUniversity.Resource.Styleable.RecyclerView_reverseLayout;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_spanCount = global::XamarinUniversity.Resource.Styleable.RecyclerView_spanCount;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_stackFromEnd = global::XamarinUniversity.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int civ_border_color = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int civ_border_overlay = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int civ_border_width = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int civ_fill_color = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int fab_colorDisabled = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int fab_colorNormal = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int fab_colorPressed = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int fab_colorRipple = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int fab_shadow = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int fab_size = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int layoutManager = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int reverseLayout = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int spanCount = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int stackFromEnd = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int fab_material_blue_500 = 2130837504;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int fab_elevation_lollipop = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int fab_scroll_threshold = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int fab_shadow_size = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int fab_size_mini = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int fab_size_normal = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int item_touch_helper_swipe_escape_max_velocity = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int item_touch_helper_swipe_escape_velocity = 2130903047;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int fab_shadow = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int fab_shadow_mini = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int icon = 2130968578;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int chatListView = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int contentTextView = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int fab = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int item_touch_helper_previous_elevation = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int messageEditText = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int messageListView = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int mini = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int nameTextView = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int normal = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int photoImageView = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int sendFab = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int ChatDetails = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int ChatRow = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int Main = 2131099650;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int app_name = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010002,0x7F010003 }
			public static int[] CircleImageView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_color = 0;
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_overlay = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_width = 2;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			// aapt resource value: { 0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008,0x7F010009 }
			public static int[] FloatingActionButton = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorDisabled = 0;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorPressed = 2;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			// aapt resource value: { 0x10100C4,0x10100F1,0x7F01000A,0x7F01000B,0x7F01000C,0x7F01000D }
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 4
			public const int RecyclerView_spanCount = 4;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
